[theme]
primaryColor = "#1F77B4"       # Corporate blue
backgroundColor = "#F9FAFB"    # Light clean background
secondaryBackgroundColor = "#E5E7EB" # Subtle gray panels
textColor = "#111827"          # Dark text for contrast
font = "sans serif"